{
	"name"        : "Rent",
	"author"      : "Clear Corp S.A.",
	"version"     : "1.0",
	"depends"     : ["base","account_asset"],
	"init_xml"    : [],
	"update_xml"  : ["rent_view.xml", 
					"rent_data.xml",
					"rent_workflow.xml", 
					'rent_contract_report.xml',
					'security/rent_security.xml',],
	"category"    : "Rent",
	"active"      : False,
	"instalable"  : True,
}
